FROM bellsoft/liberica-openjdk-alpine:11.0.16.1-1
COPY ./ ./src
RUN javac -sourcepath ./src -d ./back ./src/main/Main.java
RUN java -classpath ./back main.Main
RUN javadoc -d ./doc -sourcepath  ./src -cp ./back -subpackages CaesarCipher Main